# Camera selection
CAMERA: 0 # 0: BUILT_IN_WEBCAM, 1: EXTERNAL_WEBCAM, 2: PI_CAMERA

# Color detection mode
COLOR_MODE: 1   # 0: FIX_RANGE, 1: DYNAMIC_RANGE
REF_IMAGE: "assets/reference_image.jpg"

# GUI Flavour
GUI_FLAVOUR: "DPG" # NO_GUI, BASIC: OpenCV window, TKINTER, PYQT, DPG: DearPyGUI (not available on raspberry pi)

# Options
camera_options:
  WHITE_BALANCE: False
  GRAY_WORLD: False
  RED_NOISE_REDUCTION: False
  GLOBAL_NORMALIZATION: False
  BLUR: True

# Default Color Ranges
RED_L: [135, 135, 85]
RED_U: [195, 235, 135]

YELLOW_L: [15, 85, 120]
YELLOW_U: [40, 145, 145]

# Noise red range
RED_NOISE_L: [0, 15, 0]
RED_NOISE_U: [10, 255, 170]
